# Generated by Django 4.0.8 on 2023-02-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('primary_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Transaction_Detail', models.CharField(max_length=200)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Transaction_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
